#3월 18일 데이터베이스

#자동차정보 테이블
CREATE TABLE CAR_INFO (
	MODEL_NUMBER INT PRIMARY KEY AUTO_INCREMENT
	, MODEL_NAME VARCHAR(50) NOT NULL
	, MODEL_PRICE INT NOT NULL 
	, MANUFACTURER VARCHAR(50) NOT NULL
);

#자동차판매정보 테이블
CREATE TABLE SALES_INFO (
	SALES_NUMBER INT PRIMARY KEY AUTO_INCREMENT
	, CUSTOMER_NAME VARCHAR(50) NOT NULL
	, CUSTOMER_PHONE VARCHAR(30) NOT NULL
	, MODEL_COLOR VARCHAR(50) NOT NULL
	, SALE_DATE DATETIME NOT NULL DEFAULT SYSDATE()
	, MODEL_NUMBER INT NOT NULL REFERENCES CAR_INFO (MODEL_NUMBER)
);

SELECT * FROM CAR_INFO;
SELECT * FROM SALES_INFO;


