
CREATE TABLE ITEM_INFO (
	ITEM_NUM INT PRIMARY KEY AUTO_INCREMENT
	,ITEM_NAME VARCHAR(20) NOT NULL 
	,PRICE INT NOT NULL
	,ITEM_REGNAME VARCHAR(10)
	,ITEM_GUIDE VARCHAR(50)
	,ITEM_REGDATE DATETIME DEFAULT SYSDATE()
);

SELECT * FROM ITEM_INFO;

INSERT INTO ITEM_INFO (ITEM_NAME, PRICE, ITEM_REGNAME)
VALUES ('한겨울 패딩', 150000, '김자바');
INSERT INTO ITEM_INFO (ITEM_NAME, PRICE, ITEM_REGNAME)
VALUES ('긴 팔 셔츠', 60000, '이자바');
INSERT INTO ITEM_INFO (ITEM_NAME, PRICE, ITEM_REGNAME)
VALUES ('등산 양말', 10000, '김자바');
INSERT INTO ITEM_INFO (ITEM_NAME, PRICE, ITEM_REGNAME)
VALUES ('맨투맨', 35000, '이자바');
INSERT INTO ITEM_INFO (ITEM_NAME, PRICE, ITEM_REGNAME)
VALUES ('데님 청바지', 50000, '김자바');